### ISSUE TITLE
Background and GUI Elements Br0ke In 11.2

### ISSUE THREAD

**Issue by saphtea** [evgiz/sprit3r#2]
![image](https://user-images.githubusercontent.com/272940/50195566-82213180-02f4-11e9-8f60-4e9821249d83.png)

Hey! It might be something with SUIT or something else, I'm not sure, but there's a white background and none of the SUIT elements show unless you're hovering/clicking on them!

EDIT: OH this is using the .love binary you have on the forum, testing out the current build rn!

EDIT#2: Oh nevermind sprit3r works splendidly with 11.2! You just have to use the current git ofc :).

**Comment by saphtea** [comment]
Nevermind, I was using the build from your forum post, the git's version works splendidly. Thank you again for making this, I really appreciate it!

**Comment by evgiz** [comment]
No problem, happy to hear you found it useful!
